# Generated by Django 3.2.9 on 2022-11-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('ru', 'RUB'), ('us', 'USD')], default='ru', max_length=2),
        ),
    ]
