# Generated by Django 3.2.9 on 2022-11-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
    ]
